"""
Django settings for SpaceBook_project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================
# SECURITY / DEBUG
# ==============================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_gg57_8%(p*e_*yi(i%rf0*a1f0r63o(bwhyt=-y5(-80y@s^f"

# In production, this MUST be False
DEBUG = False

# Your public host name
ALLOWED_HOSTS = [
    "online.library.uitm.edu.my",
    "localhost",
    "127.0.0.1",
]


# ==============================
# Application definition
# ==============================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "website",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SpaceBook_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SpaceBook_project.wsgi.application"


# ==============================
# Database
# (currently SQLite – OK for testing, not ideal for big prod)
# ==============================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ==============================
# Password validation
# ==============================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ==============================
# Internationalization
# ==============================

LANGUAGE_CODE = "en-us"

# Malaysia time zone fits your environment better than UTC
TIME_ZONE = "Asia/Kuala_Lumpur"

USE_I18N = True
USE_TZ = True


# ==============================
# Static & Media files
# ==============================

# You are deploying under /spacebook, so static URLs should live there:
STATIC_URL = "/spacebook/static/"

# This is where collectstatic will dump all files
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media – you can later decide if you also want /spacebook/media/
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# ==============================
# Security behind IIS / ARR
# ==============================

# Trust HTTPS info passed from IIS / ARR
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# CSRF: trust your public domain
CSRF_TRUSTED_ORIGINS = [
    "https://online.library.uitm.edu.my",
]


# ==============================
# Default primary key field type
# ==============================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
