# Generated by Django 5.2.8 on 2025-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'branches',
                'managed': True,
            },
        ),
    ]
