# Generated by Django 5.2.8 on 2025-11-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AlterModelTable(
            name='branch',
            table=None,
        ),
    ]
