# Generated by Django 5.2.8 on 2025-12-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='Main UiTM branch, e.g. UiTM Cawangan Pulau Pinang', max_length=100)),
                ('campus_name', models.CharField(help_text='Official campus name', max_length=150)),
                ('city', models.CharField(help_text='City or district where the campus is located', max_length=100)),
                ('state', models.CharField(help_text='State in Malaysia', max_length=100)),
                ('role', models.CharField(choices=[('HQ', 'HQ'), ('Main Campus', 'Main Campus'), ('Satellite Campus', 'Satellite Campus')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('relocated', 'Relocated'), ('closed', 'Closed')], default='active', max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='Official UiTM source for verification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['branch_name', 'campus_name'],
            },
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='state',
            new_name='location',
        ),
    ]
