# Generated by Django 5.2.8 on 2025-12-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_campus_rename_state_branch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='updated_at',
        ),
    ]
