# Generated by Django 5.2.8 on 2025-12-27 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_campus_created_at_remove_campus_source_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['campus_name'], 'verbose_name': 'Campus', 'verbose_name_plural': 'Campuses'},
        ),
        migrations.RemoveField(
            model_name='campus',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='id',
        ),
        migrations.AddField(
            model_name='campus',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campuses', to='website.branch'),
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_code',
            field=models.CharField(default='', help_text='Unique campus identifier', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campus',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campus',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='campus',
            table='website_campus',
        ),
    ]
