# Generated by Django 5.2.8 on 2025-12-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_campus_options_remove_campus_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='branch',
            field=models.ForeignKey(db_column='branch_code', default='', on_delete=django.db.models.deletion.PROTECT, related_name='campuses', to='website.branch'),
            preserve_default=False,
        ),
    ]
