# Generated by Django 5.2.8 on 2025-12-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_campus_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('library_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('campus_code', models.CharField(blank=True, max_length=150, null=True)),
                ('library_name', models.TextField()),
                ('short_name', models.TextField(blank=True, null=True)),
                ('library_type', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('postcode', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('weekend_hours', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('last_verified', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
                'db_table': 'website_library',
                'ordering': ['library_name'],
            },
        ),
    ]
