# Generated by Django 5.2.8 on 2026-01-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySpace',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('space_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('space_type', models.CharField(blank=True, choices=[('study', 'Study Area'), ('discussion', 'Discussion Room'), ('media', 'Media / Lab'), ('reading', 'Reading Area'), ('other', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField()),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('has_climate_control', models.BooleanField(default=False)),
                ('noise_level', models.CharField(blank=True, choices=[('quiet', 'Quiet'), ('moderate', 'Moderate'), ('loud', 'Loud')], max_length=20)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('buffer_minutes', models.PositiveIntegerField(default=0)),
                ('advance_notice', models.PositiveIntegerField(blank=True, help_text='Hours before booking', null=True)),
                ('requires_payment', models.BooleanField(default=False)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('access_policy', models.CharField(choices=[('public', 'Public'), ('students', 'Students Only'), ('staff', 'Staff Only'), ('restricted', 'Restricted')], default='public', max_length=20)),
                ('booking_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_use', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(db_column='library_code', on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='website.library')),
            ],
            options={
                'db_table': 'library_space',
                'ordering': ['space_name'],
            },
        ),
    ]
