# Generated by Django 5.2.8 on 2026-01-19 04:24

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.library_image_upload_path),
        ),
    ]
