# Generated by Django 5.2.8 on 2026-01-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_libraryspace'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='libraryspace',
            table='website_space',
        ),
    ]
