# Generated by Django 5.2.8 on 2026-01-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_libraryspace_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryspace',
            name='has_network_node',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libraryspace',
            name='has_power_plug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libraryspace',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
    ]
