# Generated by Django 5.2.8 on 2026-01-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='UNPAID', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
