# Generated by Django 5.2.8 on 2025-12-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('LIBRARIAN', 'Librarian'), ('ADMIN', 'Administrator'), ('EXTERNAL', 'External User')], max_length=20),
        ),
    ]
