from django.urls import path
from . import views
from .views import home

urlpatterns = [
    path("", home, name="home"),
    path('student/dashboard/', views.student_dashboard, name='student_dashboard'),
    path('student/branches/list/', views.student_branches_list, name='student_branches_list'),
    path('student/spaces/list/', views.student_spaces_list, name='student_spaces_list'),
    path('student/bookings/list/', views.student_bookings_list, name='student_bookings_list'),
    path('student/bookings/availability/', views.student_bookings_availability, name='student_bookings_availability'),
    path('student/bookings/confirm/', views.student_bookings_confirm, name='student_bookings_confirm'),
    path('librarian/dashboard/', views.librarian_dashboard, name='librarian_dashboard'),
    path('librarian/bookings/pending/', views.librarian_bookings_pending, name='librarian_bookings_pending'),
    path('librarian/bookings/detail/', views.librarian_bookings_detail, name='librarian_bookings_detail'),
    path('librarian/spaces/list/', views.librarian_spaces_list, name='librarian_spaces_list'),
    path('librarian/spaces/edit/', views.librarian_spaces_edit, name='librarian_spaces_edit'),
    path('librarian/closures/list/', views.librarian_closures_list, name='librarian_closures_list'),
    path('librarian/closures/create/', views.librarian_closures_create, name='librarian_closures_create'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/libraries/list/', views.admin_libraries_list, name='admin_libraries_list'),
    path('admin/libraries/edit/', views.admin_libraries_edit, name='admin_libraries_edit'),
    path('admin/branches/list/', views.admin_branches_list, name='admin_branches_list'),
    path('admin/branches/edit/', views.admin_branches_edit, name='admin_branches_edit'),
    path('admin/users/assign-librarians/', views.admin_users_assign_librarians, name='admin_users_assign_librarians'),
    path('admin/settings/system/', views.admin_settings_system, name='admin_settings_system'),
    path('reports/dashboard/', views.reports_dashboard, name='reports_dashboard'),
    path('reports/usage/totals/', views.reports_usage_totals, name='reports_usage_totals'),
    path('reports/usage/averages/', views.reports_usage_averages, name='reports_usage_averages'),
    path('reports/usage/popular-spaces/', views.reports_usage_popular_spaces, name='reports_usage_popular_spaces'),
    path('reports/usage/branch-comparison/', views.reports_usage_branch_comparison, name='reports_usage_branch_comparison'),
    path('bank/dashboard/', views.bank_dashboard, name='bank_dashboard'),
    path('bank/payments/list/', views.bank_payments_list, name='bank_payments_list'),
    path('bank/payments/update/', views.bank_payments_update, name='bank_payments_update'),
    path('user/profile/view/', views.user_profile_view, name='user_profile_view'),
    path('user/profile/edit/', views.user_profile_edit, name='user_profile_edit'),
    path('system/audit/logs/', views.system_audit_logs, name='system_audit_logs'),
    path('system/errors/branch-closed/', views.system_errors_branch_closed, name='system_errors_branch_closed'),
    path('system/errors/conflict/', views.system_errors_conflict, name='system_errors_conflict'),
]
